name: "Test Task CI"
on:
  workflow_dispatch:

env:
  REGISTRY: ghcr.io
  IMAGE_NAME: ${{ github.repository }}

jobs:
  testing:
    runs-on: ubuntu-latest
    steps:
      - name: "Copy repos"
        uses: actions/checkout@v1

      - name: "Use Node.js 18.5.0"
        uses: actions/setup-node@v1
        with:
          node-version: "18.5.0"

      - name: "Install dependencies"
        run: "npm install"
        working-directory: ./angular
        
      - name: "Testing"
        run: "npm test -- --watch=false --browsers=ChromeHeadless"
        working-directory: ./angular

  building:
    needs: testing
    runs-on: ubuntu-latest
    steps:
      - name: "Copy repos"
        uses: actions/checkout@v1

      - name: "Use Node.js 18.5.0"
        uses: actions/setup-node@v1
        with:
          node-version: "18.5.0"

      - name: "Install dependencies"
        run: "npm install"
        working-directory: ./angular
        
      - name: "Building app"
        run: "npm run build"
        working-directory: ./angular

      - name: "Log in to the Container registry"
        uses: "docker/login-action@f054a8b539a109f9f41c372932f1ae047eff08c9"
        with:
          registry: ${{ env.REGISTRY }}
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: "Extract metadata (tags, labels) for Docker"
        id: "meta"
        uses: "docker/metadata-action@98669ae865ea3cffbcbaa878cf57c20bbf1c6c38"
        with:
          images: ${{ env.REGISTRY }}/${{ env.IMAGE_NAME }}

      - name: "Build and push Docker Image"
        uses: "docker/build-push-action@ad44023a93711e3deb337508980b4b5e9bcdc5dc"
        with:
          context: .
          push: true
          tags: ${{ steps.meta.outputs.tags }}
          labels: ${{ steps.meta.outputs.labels }}
