name: "Test task CI"
on:
  workflow_dispatch:

env:
  REGISTRY: ghcr.io
  IMAGE_NAME: ${{ github.repository }}

jobs:
  task-building:
    runs-on: ubuntu-latest
    steps:
      - name: "Getting a start time"
        if: always()
        id: "get-cur"
        run: echo "::set-output name=time::$(( `date +%s` ))"
        
      - name: "Copying repos"
        uses: actions/checkout@v1

      - name: "Use Node.js 18.5.0"
        uses: actions/setup-node@v1
        with:
          node-version: "18.5.0"

      - name: "Installing dependencies"
        run: "npm install"
        working-directory: ./angular
        
      - name: "Testing"
        run: "npm test -- --watch=false --browsers=ChromeHeadless"
        working-directory: ./angular
        
      - name: "Lint check"
        run: "npm run lint"
        working-directory: ./angular

      - name: "Stop on fail?"
        if: failure()
        run: exit 1
        
      - name: "Building"
        run: "npm run build"
        working-directory: ./angular

      - name: "Log in to the Container registry"
        uses: "docker/login-action@f054a8b539a109f9f41c372932f1ae047eff08c9"
        with:
          registry: ${{ env.REGISTRY }}
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: "Extracting metadata (tags, labels) for Docker"
        id: "meta"
        uses: "docker/metadata-action@98669ae865ea3cffbcbaa878cf57c20bbf1c6c38"
        with:
          images: ${{ env.REGISTRY }}/${{ env.IMAGE_NAME }}

      - name: "Build and push Docker Image"
        uses: "docker/build-push-action@ad44023a93711e3deb337508980b4b5e9bcdc5dc"
        with:
          context: .
          push: true
          tags: ${{ steps.meta.outputs.tags }}
          labels: ${{ steps.meta.outputs.labels }}
          
      - name: "Getting total exec time"
        if: always()
        id: "get-time"
        run: echo "::set-output name=time::$(( `date +%s` - ${{ steps.get-cur.outputs.time }} ))"
          
      - name: "Sending mail"
        if: always()
        uses: dawidd6/action-send-mail@v3
        with:
          server_address: smtp.gmail.com
          server_port: 465
          username: ${{secrets.MAIL_USERNAME}}
          password: ${{secrets.MAIL_PASSWORD}}
          subject: ${{ github.job }} job of ${{ github.repository }} has ${{ job.status }}
          body: |
                ${{ github.job }} job in workflow ${{ github.workflow }} of ${{ github.repository }} has ${{ job.status }}
                Executed in ${{ steps.get-time.outputs.time }} sec
          to: verdenart@gmail.com
          from: Test Task
